version: "3.8"

services:

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # ✅ important

  task-manager-api:
    build: .
    container_name: task-manager-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

volumes:
  mysql-data: